// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./components/Code/CodeBlock.vue')['default']
    CodeGroup: typeof import('./components/Code/CodeGroup.vue')['default']
    CodeGroupToolbar: typeof import('./components/Code/CodeGroupToolbar.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
